name: ci
on:
  push:
    branches:
      - main
      - trying
      - staging
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ci ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.threads }}t
    runs-on: ${{ matrix.os }}
    env:
      JULIA_NUM_THREADS: ${{ matrix.threads }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.12'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        threads:
          - '1'
        include:
          - version: '1.12'
            os: ubuntu-latest
            threads: '4'
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
